FROM python:3.11-slim

WORKDIR /app

COPY charts.py .
COPY requirements.txt .

RUN apt-get update && apt-get install -y --no-install-recommends \
    libfreetype6-dev \
    libpng-dev \
    fontconfig \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --default-timeout=100 \
    -i https://mirrors.aliyun.com/pypi/simple/ \
    -r requirements.txt

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "charts:app"]